name: deploy threedwear back
on: [push]
jobs:
  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: Execute commande
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            mkdir /home/dyco/poinsa
            ls -al /home/dyco

