name: Deploy Admin facscience

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t admin/admin-facscience:latest .
          docker image admin/admin-facscience:latest

      # Save Docker image as tar
      - name: Save Docker image to tar
        run: |
          mkdir -p /tmp/deploy
          docker save admin/admin-facscience:latest -o /tmp/deploy/admin-facscience.tar
          ls -lh /tmp/deploy/admin-facscience.tar
          if [ ! -s /tmp/deploy/admin-facscience.tar ]; then
            echo "Erreur : le fichier tar est vide ou n'a pas été créé"
            exit 1
          fi

      # Copy tar to server
      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "/tmp/deploy/admin-facscience.tar"
          target: "/home/dyco/poinsa/"

      # Load Docker image and deploy with docker-compose
      - name: Load and deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/dyco/poinsa
            # Charger l'im`age Docker
            docker load -i admin-facscience.tar
            # Arrêter et supprimer l'ancien conteneur si il existe
            docker-compose down || true
            # Lancer le conteneur avec docker-compose
            docker-compose up -d
            # Vérifier l'état des conteneurs
            docker ps -a
