name: Deploy Threedwear App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Build Docker image
      - name: Build Docker image
        run: |
          docker build -t threedwear-back:latest .

      # Étape 3 : Sauvegarder l'image dans un fichier .tar
      - name: Save Docker image
        run: docker save -o threedwear-back.tar threedwear-back:latest

      # Étape 4 : Copier le fichier .tar sur le serveur
      - name: Transfer Docker image to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "threedwear-back.tar"
          target: "/home/dyco/poinsa/"

      # Étape 5 : Déployer l'image sur le serveur
      - name: Deploy Docker container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            docker load -i /home/dyco/poinsa/threedwear-back.tar
            docker rm -f threedwear-back || true
            docker run -d \
              --name threedwear-back \
              -p 7000:8000 \
              threedwear-back:latest
