name: Build and Deploy React App

on:
  push:
    branches:
      - fork

jobs:
  build:
    name: Build React Project
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances et builder
      - name: Install dependencies
        run: npm ci

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Build project
        run: npm run build

      # 4️⃣ Sauvegarder le build comme artefact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build  # ← attend que le job "build" soit terminé avec succès

    steps:
      # 1️⃣ Télécharger le build du job précédent
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      # 2️⃣ Déployer via SSH (SCP)
      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "build/*"
          target: "/home/sciadm/test"

      # 3️⃣ Ajuster les permissions (optionnel)
      - name: Fix permissions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            sudo chown -R www-data:www-data /home/sciadm/test
            sudo chmod -R 755 /home/sciadm/test
            ls -al /home/sciadm/test
